const pages=window.BOOK_PAGES;let current=0;const book=document.getElementById('book');const currentEl=document.getElementById('pageCurrent');const totalEl=document.getElementById('pageTotal');const prev=document.getElementById('prevBtn');const next=document.getElementById('nextBtn');const sidebar=document.getElementById('sidebar');const overlay=document.getElementById('overlay');
totalEl.textContent=pages.length;
function esc(s){return String(s).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}
function render(){const p=pages[current];let inner='';if(p.kind==='cover'){inner=`<div class="cover-shape"></div><div class="cover-shape2"></div><div class="cover-content"><div class="cpp-badge">C++</div><div class="cover-title">С++ МАШИНАҒА БАҒЫТТАЛҒАН БАҒДАРЛАМАЛАУ</div><div class="cover-sub">Заманауи электронды оқу құралы</div><div class="cover-corner">ONLINE BOOK · 2026</div></div>`}
else if(p.kind==='info'){inner=`<div class="info"><div class="info-box"><div class="smallcap">Электронды оқу құралы</div><h1>${esc(p.title)}</h1>${p.content}</div></div>`}
else{inner=`<div class="page-meta"><span>${esc(p.section||'')}</span><span>${p.source_page?'Бастапқы материал: '+p.source_page+'-бет':''}</span></div>${p.title?`<h1>${esc(p.title)}</h1>`:''}${p.content}`}
inner+=`<div class="page-no">${current+1}</div>`;book.innerHTML=`<article class="paper ${p.kind==='cover'?'cover':''} ${p.kind==='info'?'info':''}">${inner}</article>`;currentEl.textContent=current+1;prev.disabled=current===0;next.disabled=current===pages.length-1;document.querySelectorAll('[data-jump]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();go(Number(a.dataset.jump));closeSide();}));
}
function go(i){if(i<0||i>=pages.length)return;current=i;render();window.scrollTo({top:0,behavior:'smooth'});}
prev.onclick=()=>go(current-1);next.onclick=()=>go(current+1);document.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')go(current-1);if(e.key==='ArrowRight'||e.key===' ')go(current+1);if(e.key==='Escape')closeSide()});
function openSide(){sidebar.classList.add('open');overlay.classList.add('show')}function closeSide(){sidebar.classList.remove('open');overlay.classList.remove('show')}document.getElementById('menuBtn').onclick=openSide;document.getElementById('closeMenu').onclick=closeSide;overlay.onclick=closeSide;
function buildSide(){let html='<div class="side-section"><h4>Дәрістер</h4>';pages.forEach((p,i)=>{if(p.kind==='lecture'&&p.title)html+=`<a href="#" class="side-link" data-jump="${i}">${esc(p.title)}</a>`});html+='</div><div class="side-section"><h4>Зертханалық жұмыстар</h4>';pages.forEach((p,i)=>{if(p.kind==='lab'&&p.title)html+=`<a href="#" class="side-link" data-jump="${i}">${esc(p.title)}</a>`});html+='</div><div class="side-section"><h4>Бастапқы материалдар</h4><a class="side-link" href="source/lectures.pdf" target="_blank">Дәрістер жиынтығы (PDF)</a><a class="side-link" href="source/labs.pdf" target="_blank">Зертханалық жұмыстар (PDF)</a></div>';document.getElementById('tocSide').innerHTML=html;document.querySelectorAll('#tocSide [data-jump]').forEach(a=>a.onclick=e=>{e.preventDefault();go(Number(a.dataset.jump));closeSide()})}
document.getElementById('themeBtn').onclick=()=>document.body.classList.toggle('dark');document.getElementById('fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();buildSide();render();
